// <auto-generated />
namespace ThirteenDaysAWeek.iFlyShop.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class productinitialadd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(productinitialadd));
        
        string IMigrationMetadata.Id
        {
            get { return "201812131645390_product-initial-add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
